name: Terraform

on:
  push:
    branches:
      - '*'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0
    
    - name: Setup Google Cloud SDK
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo $GOOGLE_APPLICATION_CREDENTIALS | base64 -d > /tmp/keyfile.json
        gcloud auth activate-service-account --key-file=/tmp/keyfile.json
    
    - name: Manual approval
      if: github.ref != 'refs/heads/main' && github.event_name != 'pull_request'
      run: |
        echo "This workflow is being run on a branch other than main. Do you want to proceed?"
        read -p "Enter 'yes' to proceed: " confirmation
        if [ "$confirmation" != "yes" ]; then
          echo "Workflow cancelled."
          exit 1
        fi
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve